### PR TITLE
Added api doc generation

### PR DESCRIPTION
**Pull request by Max13**
My bad. I did the generation with [`sami`](https://github.com/FriendsOfPHP/Sami) instead of `Doxygen`.

I added the config file also, the index pane is generated, I don't know how to remove it but on small window it is hidden (=D)

### CODE REVIEW

**Comment by claytonrcarter** [comment]
Awesome, thanks!

**Comment by Max13** [comment]
Now, you just need to send another PR because Kapeli merged yours already 😂

**Comment by Max13** [comment]
Sorry for not having double-checked all the small changes you had to do in `generate.bash` and `sami-config.php`

**Comment by claytonrcarter** [comment]
All good, no worries! I definitely wouldn't have figured it out on my own.

**Pull request merged**
